### ISSUE TITLE
Test that the tap works using Travis-CI's Mac OS X

### ISSUE THREAD

**Issue by zmughal** [project-renard/homebrew-project-renard#1]
See this example [`.travis.yml`](http://stackoverflow.com/questions/20396325/using-travis-ci-to-test-homebrew-tap).

``` yaml
language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=first_package
  - PACKAGE=second_package
  ...
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE
```
